language: node_js
node_js: stable

# 只监听 source 分支的改动
branches:
  only:
    - blog-source

env:
  global:
    - GH_REF: github.com/YongMaple/YongMaple.github.io.git
# 缓存依赖，节省持续集成时间
cache:
  yarn: true
  directories:
    - node_modules
    # - themes

before_install:
  - git config user.name "YongMaple"
  - git config user.email "740534248@qq.com"
  # 由于使用了yarn，所以需要下载，如不用yarn这两行可以删除
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install -g hexo-cli
# S: Build Lifecycle
install:
  - yarn

#before_script:
# - npm install -g gulp

script:
  - hexo clean
  - hexo generate

after_script:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
